name: 2021-cfde-rnaseq-in-cloud
channels:
    - conda-forge
    - bioconda
    - defaults
dependencies:
    - r-base=4.0.5
    - r-irkernel=1.1
    - r-devtools
    - r-stringr
    - r-stringi
    - r-data.table
    - r-dplyr
    - r-numbers
    - osfclient
